/* tslint:disable */
/* eslint-disable */
/**
 * api/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GoLoadCreateAccountRequest,
  GoLoadCreateAccountResponse,
  GoLoadCreateDownloadTaskRequest,
  GoLoadCreateDownloadTaskResponse,
  GoLoadCreateSessionRequest,
  GoLoadCreateSessionResponse,
  RpcStatus,
} from '../models/index';
import {
    GoLoadCreateAccountRequestFromJSON,
    GoLoadCreateAccountRequestToJSON,
    GoLoadCreateAccountResponseFromJSON,
    GoLoadCreateAccountResponseToJSON,
    GoLoadCreateDownloadTaskRequestFromJSON,
    GoLoadCreateDownloadTaskRequestToJSON,
    GoLoadCreateDownloadTaskResponseFromJSON,
    GoLoadCreateDownloadTaskResponseToJSON,
    GoLoadCreateSessionRequestFromJSON,
    GoLoadCreateSessionRequestToJSON,
    GoLoadCreateSessionResponseFromJSON,
    GoLoadCreateSessionResponseToJSON,
    RpcStatusFromJSON,
    RpcStatusToJSON,
} from '../models/index';

export interface GoLoadServiceCreateAccountRequest {
    body: GoLoadCreateAccountRequest;
}

export interface GoLoadServiceCreateDownloadTaskRequest {
    body: GoLoadCreateDownloadTaskRequest;
}

export interface GoLoadServiceCreateSessionRequest {
    body: GoLoadCreateSessionRequest;
}

/**
 * 
 */
export class GoLoadServiceApi extends runtime.BaseAPI {

    /**
     */
    async goLoadServiceCreateAccountRaw(requestParameters: GoLoadServiceCreateAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GoLoadCreateAccountResponse>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling goLoadServiceCreateAccount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/go_load.GoLoadService/CreateAccount`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GoLoadCreateAccountRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GoLoadCreateAccountResponseFromJSON(jsonValue));
    }

    /**
     */
    async goLoadServiceCreateAccount(requestParameters: GoLoadServiceCreateAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GoLoadCreateAccountResponse> {
        const response = await this.goLoadServiceCreateAccountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async goLoadServiceCreateDownloadTaskRaw(requestParameters: GoLoadServiceCreateDownloadTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GoLoadCreateDownloadTaskResponse>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling goLoadServiceCreateDownloadTask().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/go_load.GoLoadService/CreateDownloadTask`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GoLoadCreateDownloadTaskRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GoLoadCreateDownloadTaskResponseFromJSON(jsonValue));
    }

    /**
     */
    async goLoadServiceCreateDownloadTask(requestParameters: GoLoadServiceCreateDownloadTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GoLoadCreateDownloadTaskResponse> {
        const response = await this.goLoadServiceCreateDownloadTaskRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async goLoadServiceCreateSessionRaw(requestParameters: GoLoadServiceCreateSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GoLoadCreateSessionResponse>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling goLoadServiceCreateSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/go_load.GoLoadService/CreateSession`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GoLoadCreateSessionRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GoLoadCreateSessionResponseFromJSON(jsonValue));
    }

    /**
     */
    async goLoadServiceCreateSession(requestParameters: GoLoadServiceCreateSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GoLoadCreateSessionResponse> {
        const response = await this.goLoadServiceCreateSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
