/* tslint:disable */
/* eslint-disable */
/**
 * api/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GoLoadCreateAccountResponse
 */
export interface GoLoadCreateAccountResponse {
    /**
     * 
     * @type {string}
     * @memberof GoLoadCreateAccountResponse
     */
    accountId?: string;
}

/**
 * Check if a given object implements the GoLoadCreateAccountResponse interface.
 */
export function instanceOfGoLoadCreateAccountResponse(value: object): value is GoLoadCreateAccountResponse {
    return true;
}

export function GoLoadCreateAccountResponseFromJSON(json: any): GoLoadCreateAccountResponse {
    return GoLoadCreateAccountResponseFromJSONTyped(json, false);
}

export function GoLoadCreateAccountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoLoadCreateAccountResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
    };
}

export function GoLoadCreateAccountResponseToJSON(value?: GoLoadCreateAccountResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'accountId': value['accountId'],
    };
}

