/* tslint:disable */
/* eslint-disable */
/**
 * api/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GoLoadAccount } from './GoLoadAccount';
import {
    GoLoadAccountFromJSON,
    GoLoadAccountFromJSONTyped,
    GoLoadAccountToJSON,
} from './GoLoadAccount';
import type { GoLoadDownloadStatus } from './GoLoadDownloadStatus';
import {
    GoLoadDownloadStatusFromJSON,
    GoLoadDownloadStatusFromJSONTyped,
    GoLoadDownloadStatusToJSON,
} from './GoLoadDownloadStatus';
import type { GoLoadDownloadType } from './GoLoadDownloadType';
import {
    GoLoadDownloadTypeFromJSON,
    GoLoadDownloadTypeFromJSONTyped,
    GoLoadDownloadTypeToJSON,
} from './GoLoadDownloadType';

/**
 * 
 * @export
 * @interface GoLoadDownloadTask
 */
export interface GoLoadDownloadTask {
    /**
     * 
     * @type {string}
     * @memberof GoLoadDownloadTask
     */
    id?: string;
    /**
     * 
     * @type {GoLoadAccount}
     * @memberof GoLoadDownloadTask
     */
    ofAccount?: GoLoadAccount;
    /**
     * 
     * @type {GoLoadDownloadType}
     * @memberof GoLoadDownloadTask
     */
    downloadType?: GoLoadDownloadType;
    /**
     * 
     * @type {string}
     * @memberof GoLoadDownloadTask
     */
    url?: string;
    /**
     * 
     * @type {GoLoadDownloadStatus}
     * @memberof GoLoadDownloadTask
     */
    downloadStatus?: GoLoadDownloadStatus;
}

/**
 * Check if a given object implements the GoLoadDownloadTask interface.
 */
export function instanceOfGoLoadDownloadTask(value: object): value is GoLoadDownloadTask {
    return true;
}

export function GoLoadDownloadTaskFromJSON(json: any): GoLoadDownloadTask {
    return GoLoadDownloadTaskFromJSONTyped(json, false);
}

export function GoLoadDownloadTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoLoadDownloadTask {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'ofAccount': json['ofAccount'] == null ? undefined : GoLoadAccountFromJSON(json['ofAccount']),
        'downloadType': json['downloadType'] == null ? undefined : GoLoadDownloadTypeFromJSON(json['downloadType']),
        'url': json['url'] == null ? undefined : json['url'],
        'downloadStatus': json['downloadStatus'] == null ? undefined : GoLoadDownloadStatusFromJSON(json['downloadStatus']),
    };
}

export function GoLoadDownloadTaskToJSON(value?: GoLoadDownloadTask | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'ofAccount': GoLoadAccountToJSON(value['ofAccount']),
        'downloadType': GoLoadDownloadTypeToJSON(value['downloadType']),
        'url': value['url'],
        'downloadStatus': GoLoadDownloadStatusToJSON(value['downloadStatus']),
    };
}

