/* tslint:disable */
/* eslint-disable */
/**
 * api/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GoLoadGetDownloadTaskFileResponse
 */
export interface GoLoadGetDownloadTaskFileResponse {
    /**
     * 
     * @type {string}
     * @memberof GoLoadGetDownloadTaskFileResponse
     */
    data?: string;
}

/**
 * Check if a given object implements the GoLoadGetDownloadTaskFileResponse interface.
 */
export function instanceOfGoLoadGetDownloadTaskFileResponse(value: object): value is GoLoadGetDownloadTaskFileResponse {
    return true;
}

export function GoLoadGetDownloadTaskFileResponseFromJSON(json: any): GoLoadGetDownloadTaskFileResponse {
    return GoLoadGetDownloadTaskFileResponseFromJSONTyped(json, false);
}

export function GoLoadGetDownloadTaskFileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoLoadGetDownloadTaskFileResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function GoLoadGetDownloadTaskFileResponseToJSON(value?: GoLoadGetDownloadTaskFileResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': value['data'],
    };
}

