/* tslint:disable */
/* eslint-disable */
/**
 * api/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GoLoadUpdateDownloadTaskRequest
 */
export interface GoLoadUpdateDownloadTaskRequest {
    /**
     * 
     * @type {string}
     * @memberof GoLoadUpdateDownloadTaskRequest
     */
    downloadTaskId?: string;
    /**
     * 
     * @type {string}
     * @memberof GoLoadUpdateDownloadTaskRequest
     */
    url?: string;
}

/**
 * Check if a given object implements the GoLoadUpdateDownloadTaskRequest interface.
 */
export function instanceOfGoLoadUpdateDownloadTaskRequest(value: object): value is GoLoadUpdateDownloadTaskRequest {
    return true;
}

export function GoLoadUpdateDownloadTaskRequestFromJSON(json: any): GoLoadUpdateDownloadTaskRequest {
    return GoLoadUpdateDownloadTaskRequestFromJSONTyped(json, false);
}

export function GoLoadUpdateDownloadTaskRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoLoadUpdateDownloadTaskRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'downloadTaskId': json['downloadTaskId'] == null ? undefined : json['downloadTaskId'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function GoLoadUpdateDownloadTaskRequestToJSON(value?: GoLoadUpdateDownloadTaskRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'downloadTaskId': value['downloadTaskId'],
        'url': value['url'],
    };
}

