/* tslint:disable */
/* eslint-disable */
/**
 * api/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GoLoadCreateAccountRequest
 */
export interface GoLoadCreateAccountRequest {
    /**
     * 
     * @type {string}
     * @memberof GoLoadCreateAccountRequest
     */
    accountName?: string;
    /**
     * 
     * @type {string}
     * @memberof GoLoadCreateAccountRequest
     */
    password?: string;
}

/**
 * Check if a given object implements the GoLoadCreateAccountRequest interface.
 */
export function instanceOfGoLoadCreateAccountRequest(value: object): value is GoLoadCreateAccountRequest {
    return true;
}

export function GoLoadCreateAccountRequestFromJSON(json: any): GoLoadCreateAccountRequest {
    return GoLoadCreateAccountRequestFromJSONTyped(json, false);
}

export function GoLoadCreateAccountRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoLoadCreateAccountRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accountName': json['accountName'] == null ? undefined : json['accountName'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function GoLoadCreateAccountRequestToJSON(value?: GoLoadCreateAccountRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'accountName': value['accountName'],
        'password': value['password'],
    };
}

