/* tslint:disable */
/* eslint-disable */
/**
 * api/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GoLoadDownloadTask } from './GoLoadDownloadTask';
import {
    GoLoadDownloadTaskFromJSON,
    GoLoadDownloadTaskFromJSONTyped,
    GoLoadDownloadTaskToJSON,
} from './GoLoadDownloadTask';

/**
 * 
 * @export
 * @interface GoLoadUpdateDownloadTaskResponse
 */
export interface GoLoadUpdateDownloadTaskResponse {
    /**
     * 
     * @type {GoLoadDownloadTask}
     * @memberof GoLoadUpdateDownloadTaskResponse
     */
    downloadTask?: GoLoadDownloadTask;
}

/**
 * Check if a given object implements the GoLoadUpdateDownloadTaskResponse interface.
 */
export function instanceOfGoLoadUpdateDownloadTaskResponse(value: object): value is GoLoadUpdateDownloadTaskResponse {
    return true;
}

export function GoLoadUpdateDownloadTaskResponseFromJSON(json: any): GoLoadUpdateDownloadTaskResponse {
    return GoLoadUpdateDownloadTaskResponseFromJSONTyped(json, false);
}

export function GoLoadUpdateDownloadTaskResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoLoadUpdateDownloadTaskResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'downloadTask': json['downloadTask'] == null ? undefined : GoLoadDownloadTaskFromJSON(json['downloadTask']),
    };
}

export function GoLoadUpdateDownloadTaskResponseToJSON(value?: GoLoadUpdateDownloadTaskResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'downloadTask': GoLoadDownloadTaskToJSON(value['downloadTask']),
    };
}

