/* tslint:disable */
/* eslint-disable */
/**
 * api/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GoLoadGetDownloadTaskFileRequest
 */
export interface GoLoadGetDownloadTaskFileRequest {
    /**
     * 
     * @type {string}
     * @memberof GoLoadGetDownloadTaskFileRequest
     */
    downloadTaskId?: string;
}

/**
 * Check if a given object implements the GoLoadGetDownloadTaskFileRequest interface.
 */
export function instanceOfGoLoadGetDownloadTaskFileRequest(value: object): value is GoLoadGetDownloadTaskFileRequest {
    return true;
}

export function GoLoadGetDownloadTaskFileRequestFromJSON(json: any): GoLoadGetDownloadTaskFileRequest {
    return GoLoadGetDownloadTaskFileRequestFromJSONTyped(json, false);
}

export function GoLoadGetDownloadTaskFileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoLoadGetDownloadTaskFileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'downloadTaskId': json['downloadTaskId'] == null ? undefined : json['downloadTaskId'],
    };
}

export function GoLoadGetDownloadTaskFileRequestToJSON(value?: GoLoadGetDownloadTaskFileRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'downloadTaskId': value['downloadTaskId'],
    };
}

