/* tslint:disable */
/* eslint-disable */
/**
 * api/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GoLoadDownloadType } from './GoLoadDownloadType';
import {
    GoLoadDownloadTypeFromJSON,
    GoLoadDownloadTypeFromJSONTyped,
    GoLoadDownloadTypeToJSON,
} from './GoLoadDownloadType';

/**
 * 
 * @export
 * @interface GoLoadCreateDownloadTaskRequest
 */
export interface GoLoadCreateDownloadTaskRequest {
    /**
     * 
     * @type {GoLoadDownloadType}
     * @memberof GoLoadCreateDownloadTaskRequest
     */
    downloadType?: GoLoadDownloadType;
    /**
     * 
     * @type {string}
     * @memberof GoLoadCreateDownloadTaskRequest
     */
    url?: string;
}

/**
 * Check if a given object implements the GoLoadCreateDownloadTaskRequest interface.
 */
export function instanceOfGoLoadCreateDownloadTaskRequest(value: object): value is GoLoadCreateDownloadTaskRequest {
    return true;
}

export function GoLoadCreateDownloadTaskRequestFromJSON(json: any): GoLoadCreateDownloadTaskRequest {
    return GoLoadCreateDownloadTaskRequestFromJSONTyped(json, false);
}

export function GoLoadCreateDownloadTaskRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoLoadCreateDownloadTaskRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'downloadType': json['downloadType'] == null ? undefined : GoLoadDownloadTypeFromJSON(json['downloadType']),
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function GoLoadCreateDownloadTaskRequestToJSON(value?: GoLoadCreateDownloadTaskRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'downloadType': GoLoadDownloadTypeToJSON(value['downloadType']),
        'url': value['url'],
    };
}

