/* tslint:disable */
/* eslint-disable */
/**
 * api/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GoLoadAccount } from './GoLoadAccount';
import {
    GoLoadAccountFromJSON,
    GoLoadAccountFromJSONTyped,
    GoLoadAccountToJSON,
} from './GoLoadAccount';

/**
 * 
 * @export
 * @interface GoLoadCreateSessionResponse
 */
export interface GoLoadCreateSessionResponse {
    /**
     * 
     * @type {GoLoadAccount}
     * @memberof GoLoadCreateSessionResponse
     */
    account?: GoLoadAccount;
}

/**
 * Check if a given object implements the GoLoadCreateSessionResponse interface.
 */
export function instanceOfGoLoadCreateSessionResponse(value: object): value is GoLoadCreateSessionResponse {
    return true;
}

export function GoLoadCreateSessionResponseFromJSON(json: any): GoLoadCreateSessionResponse {
    return GoLoadCreateSessionResponseFromJSONTyped(json, false);
}

export function GoLoadCreateSessionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoLoadCreateSessionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'account': json['account'] == null ? undefined : GoLoadAccountFromJSON(json['account']),
    };
}

export function GoLoadCreateSessionResponseToJSON(value?: GoLoadCreateSessionResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'account': GoLoadAccountToJSON(value['account']),
    };
}

