/* tslint:disable */
/* eslint-disable */
/**
 * api/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GoLoadDownloadTask } from './GoLoadDownloadTask';
import {
    GoLoadDownloadTaskFromJSON,
    GoLoadDownloadTaskFromJSONTyped,
    GoLoadDownloadTaskToJSON,
} from './GoLoadDownloadTask';

/**
 * 
 * @export
 * @interface GoLoadGetDownloadTaskListResponse
 */
export interface GoLoadGetDownloadTaskListResponse {
    /**
     * 
     * @type {Array<GoLoadDownloadTask>}
     * @memberof GoLoadGetDownloadTaskListResponse
     */
    downloadTaskList?: Array<GoLoadDownloadTask>;
    /**
     * 
     * @type {string}
     * @memberof GoLoadGetDownloadTaskListResponse
     */
    totalCount?: string;
}

/**
 * Check if a given object implements the GoLoadGetDownloadTaskListResponse interface.
 */
export function instanceOfGoLoadGetDownloadTaskListResponse(value: object): value is GoLoadGetDownloadTaskListResponse {
    return true;
}

export function GoLoadGetDownloadTaskListResponseFromJSON(json: any): GoLoadGetDownloadTaskListResponse {
    return GoLoadGetDownloadTaskListResponseFromJSONTyped(json, false);
}

export function GoLoadGetDownloadTaskListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoLoadGetDownloadTaskListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'downloadTaskList': json['downloadTaskList'] == null ? undefined : ((json['downloadTaskList'] as Array<any>).map(GoLoadDownloadTaskFromJSON)),
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
    };
}

export function GoLoadGetDownloadTaskListResponseToJSON(value?: GoLoadGetDownloadTaskListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'downloadTaskList': value['downloadTaskList'] == null ? undefined : ((value['downloadTaskList'] as Array<any>).map(GoLoadDownloadTaskToJSON)),
        'totalCount': value['totalCount'],
    };
}

