/* tslint:disable */
/* eslint-disable */
/**
 * api/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GoLoadStreamResponse
 */
export interface GoLoadStreamResponse {
    /**
     * 
     * @type {string}
     * @memberof GoLoadStreamResponse
     */
    data?: string;
}

/**
 * Check if a given object implements the GoLoadStreamResponse interface.
 */
export function instanceOfGoLoadStreamResponse(value: object): value is GoLoadStreamResponse {
    return true;
}

export function GoLoadStreamResponseFromJSON(json: any): GoLoadStreamResponse {
    return GoLoadStreamResponseFromJSONTyped(json, false);
}

export function GoLoadStreamResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoLoadStreamResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function GoLoadStreamResponseToJSON(value?: GoLoadStreamResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': value['data'],
    };
}

