/* tslint:disable */
/* eslint-disable */
/**
 * api/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GoLoadCreateSessionRequest
 */
export interface GoLoadCreateSessionRequest {
    /**
     * 
     * @type {string}
     * @memberof GoLoadCreateSessionRequest
     */
    accountName?: string;
    /**
     * 
     * @type {string}
     * @memberof GoLoadCreateSessionRequest
     */
    password?: string;
}

/**
 * Check if a given object implements the GoLoadCreateSessionRequest interface.
 */
export function instanceOfGoLoadCreateSessionRequest(value: object): value is GoLoadCreateSessionRequest {
    return true;
}

export function GoLoadCreateSessionRequestFromJSON(json: any): GoLoadCreateSessionRequest {
    return GoLoadCreateSessionRequestFromJSONTyped(json, false);
}

export function GoLoadCreateSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoLoadCreateSessionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accountName': json['accountName'] == null ? undefined : json['accountName'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function GoLoadCreateSessionRequestToJSON(value?: GoLoadCreateSessionRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'accountName': value['accountName'],
        'password': value['password'],
    };
}

