/* tslint:disable */
/* eslint-disable */
/**
 * api/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GoLoadDownloadTask } from './GoLoadDownloadTask';
import {
    GoLoadDownloadTaskFromJSON,
    GoLoadDownloadTaskFromJSONTyped,
    GoLoadDownloadTaskToJSON,
} from './GoLoadDownloadTask';

/**
 * 
 * @export
 * @interface GoLoadCreateDownloadTaskResponse
 */
export interface GoLoadCreateDownloadTaskResponse {
    /**
     * 
     * @type {GoLoadDownloadTask}
     * @memberof GoLoadCreateDownloadTaskResponse
     */
    downloadTask?: GoLoadDownloadTask;
}

/**
 * Check if a given object implements the GoLoadCreateDownloadTaskResponse interface.
 */
export function instanceOfGoLoadCreateDownloadTaskResponse(value: object): value is GoLoadCreateDownloadTaskResponse {
    return true;
}

export function GoLoadCreateDownloadTaskResponseFromJSON(json: any): GoLoadCreateDownloadTaskResponse {
    return GoLoadCreateDownloadTaskResponseFromJSONTyped(json, false);
}

export function GoLoadCreateDownloadTaskResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoLoadCreateDownloadTaskResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'downloadTask': json['downloadTask'] == null ? undefined : GoLoadDownloadTaskFromJSON(json['downloadTask']),
    };
}

export function GoLoadCreateDownloadTaskResponseToJSON(value?: GoLoadCreateDownloadTaskResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'downloadTask': GoLoadDownloadTaskToJSON(value['downloadTask']),
    };
}

