/* tslint:disable */
/* eslint-disable */
/**
 * api/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GoLoadDeleteDownloadTaskRequest
 */
export interface GoLoadDeleteDownloadTaskRequest {
    /**
     * 
     * @type {string}
     * @memberof GoLoadDeleteDownloadTaskRequest
     */
    downloadTaskId?: string;
}

/**
 * Check if a given object implements the GoLoadDeleteDownloadTaskRequest interface.
 */
export function instanceOfGoLoadDeleteDownloadTaskRequest(value: object): value is GoLoadDeleteDownloadTaskRequest {
    return true;
}

export function GoLoadDeleteDownloadTaskRequestFromJSON(json: any): GoLoadDeleteDownloadTaskRequest {
    return GoLoadDeleteDownloadTaskRequestFromJSONTyped(json, false);
}

export function GoLoadDeleteDownloadTaskRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoLoadDeleteDownloadTaskRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'downloadTaskId': json['downloadTaskId'] == null ? undefined : json['downloadTaskId'],
    };
}

export function GoLoadDeleteDownloadTaskRequestToJSON(value?: GoLoadDeleteDownloadTaskRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'downloadTaskId': value['downloadTaskId'],
    };
}

