/* tslint:disable */
/* eslint-disable */
/**
 * api/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcStatus } from './RpcStatus';
import {
    RpcStatusFromJSON,
    RpcStatusFromJSONTyped,
    RpcStatusToJSON,
} from './RpcStatus';
import type { GoLoadGetDownloadTaskFileResponse } from './GoLoadGetDownloadTaskFileResponse';
import {
    GoLoadGetDownloadTaskFileResponseFromJSON,
    GoLoadGetDownloadTaskFileResponseFromJSONTyped,
    GoLoadGetDownloadTaskFileResponseToJSON,
} from './GoLoadGetDownloadTaskFileResponse';

/**
 * 
 * @export
 * @interface StreamResultOfGoLoadGetDownloadTaskFileResponse
 */
export interface StreamResultOfGoLoadGetDownloadTaskFileResponse {
    /**
     * 
     * @type {GoLoadGetDownloadTaskFileResponse}
     * @memberof StreamResultOfGoLoadGetDownloadTaskFileResponse
     */
    result?: GoLoadGetDownloadTaskFileResponse;
    /**
     * 
     * @type {RpcStatus}
     * @memberof StreamResultOfGoLoadGetDownloadTaskFileResponse
     */
    error?: RpcStatus;
}

/**
 * Check if a given object implements the StreamResultOfGoLoadGetDownloadTaskFileResponse interface.
 */
export function instanceOfStreamResultOfGoLoadGetDownloadTaskFileResponse(value: object): value is StreamResultOfGoLoadGetDownloadTaskFileResponse {
    return true;
}

export function StreamResultOfGoLoadGetDownloadTaskFileResponseFromJSON(json: any): StreamResultOfGoLoadGetDownloadTaskFileResponse {
    return StreamResultOfGoLoadGetDownloadTaskFileResponseFromJSONTyped(json, false);
}

export function StreamResultOfGoLoadGetDownloadTaskFileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StreamResultOfGoLoadGetDownloadTaskFileResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'] == null ? undefined : GoLoadGetDownloadTaskFileResponseFromJSON(json['result']),
        'error': json['error'] == null ? undefined : RpcStatusFromJSON(json['error']),
    };
}

export function StreamResultOfGoLoadGetDownloadTaskFileResponseToJSON(value?: StreamResultOfGoLoadGetDownloadTaskFileResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'result': GoLoadGetDownloadTaskFileResponseToJSON(value['result']),
        'error': RpcStatusToJSON(value['error']),
    };
}

